title: Brindley
views:
  - !include views/base_tablet.yaml
  - !include views/chores.yaml
  - !include views/plants.yaml
  - !include views/basement.yaml
  - !include views/spotify.yaml
  - !include views/security.yaml
  - !include views/map.yaml
